//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Token {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Token() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Token", typeof(Token).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Code.
        /// </summary>
        public static string ActiveCode {
            get {
                return ResourceManager.GetString("ActiveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Email.
        /// </summary>
        public static string ActiveEmail {
            get {
                return ResourceManager.GetString("ActiveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Album Type.
        /// </summary>
        public static string AddAlbumType {
            get {
                return ResourceManager.GetString("AddAlbumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add And Update Enquiry.
        /// </summary>
        public static string AddAndUpdateEnquiry {
            get {
                return ResourceManager.GetString("AddAndUpdateEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add And Update Event.
        /// </summary>
        public static string AddAndUpdateEvent {
            get {
                return ResourceManager.GetString("AddAndUpdateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Enquiry.
        /// </summary>
        public static string AddEnquiry {
            get {
                return ResourceManager.GetString("AddEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Event.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Events.
        /// </summary>
        public static string AddEvents {
            get {
                return ResourceManager.GetString("AddEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Branch.
        /// </summary>
        public static string AddNewBranch {
            get {
                return ResourceManager.GetString("AddNewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Country.
        /// </summary>
        public static string AddNewCountry {
            get {
                return ResourceManager.GetString("AddNewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Enquiry.
        /// </summary>
        public static string AddNewEnquiry {
            get {
                return ResourceManager.GetString("AddNewEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Enquiry Type.
        /// </summary>
        public static string AddNewEnquiryType {
            get {
                return ResourceManager.GetString("AddNewEnquiryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Event.
        /// </summary>
        public static string AddNewEvent {
            get {
                return ResourceManager.GetString("AddNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Notes.
        /// </summary>
        public static string AddNewNotes {
            get {
                return ResourceManager.GetString("AddNewNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Package.
        /// </summary>
        public static string AddNewPackage {
            get {
                return ResourceManager.GetString("AddNewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New PrintNames Type.
        /// </summary>
        public static string AddNewPrintNamesType {
            get {
                return ResourceManager.GetString("AddNewPrintNamesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Status.
        /// </summary>
        public static string AddStatus {
            get {
                return ResourceManager.GetString("AddStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Types.
        /// </summary>
        public static string AlbumTypes {
            get {
                return ResourceManager.GetString("AlbumTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Paste The Code In Application.
        /// </summary>
        public static string AndPasteTheCodeInAppication {
            get {
                return ResourceManager.GetString("AndPasteTheCodeInAppication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layan.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transfer Deposit.
        /// </summary>
        public static string BankTransferDeposit {
            get {
                return ResourceManager.GetString("BankTransferDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Add.
        /// </summary>
        public static string CanAdd {
            get {
                return ResourceManager.GetString("CanAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Delete.
        /// </summary>
        public static string CanDelete {
            get {
                return ResourceManager.GetString("CanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Display.
        /// </summary>
        public static string CanDisplay {
            get {
                return ResourceManager.GetString("CanDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Edit.
        /// </summary>
        public static string CanEdit {
            get {
                return ResourceManager.GetString("CanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Delete him Becuse It Is Used.
        /// </summary>
        public static string CanNotDeleteBecuseIsUsed {
            get {
                return ResourceManager.GetString("CanNotDeleteBecuseIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Duplicate Branch Manger.
        /// </summary>
        public static string CanNotDuplicateBranchManger {
            get {
                return ResourceManager.GetString("CanNotDuplicateBranchManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Duplicate Event With One Enquiry.
        /// </summary>
        public static string CanNotDuplicateEventWithOneEnquiry {
            get {
                return ResourceManager.GetString("CanNotDuplicateEventWithOneEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Save Custom Logo.
        /// </summary>
        public static string CanNotsAveCustomLogo {
            get {
                return ResourceManager.GetString("CanNotsAveCustomLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinet.
        /// </summary>
        public static string Clinet {
            get {
                return ResourceManager.GetString("Clinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinet Is Not Payment.
        /// </summary>
        public static string ClinetIsNotPayment {
            get {
                return ResourceManager.GetString("ClinetIsNotPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Not Found.
        /// </summary>
        public static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date From.
        /// </summary>
        public static string CreateDateFrom {
            get {
                return ResourceManager.GetString("CreateDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date Time.
        /// </summary>
        public static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date To.
        /// </summary>
        public static string CreateDateTo {
            get {
                return ResourceManager.GetString("CreateDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Of Work.
        /// </summary>
        public static string DistributionOfWork {
            get {
                return ResourceManager.GetString("DistributionOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email It Is Already Used With Another Account.
        /// </summary>
        public static string EmailItIsAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailItIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquires.
        /// </summary>
        public static string Enquires {
            get {
                return ResourceManager.GetString("Enquires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Information.
        /// </summary>
        public static string EnquiryInformation {
            get {
                return ResourceManager.GetString("EnquiryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Is Closed.
        /// </summary>
        public static string EnquiryIsClosed {
            get {
                return ResourceManager.GetString("EnquiryIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Type.
        /// </summary>
        public static string EnquiryType {
            get {
                return ResourceManager.GetString("EnquiryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Types.
        /// </summary>
        public static string EnquiryTypes {
            get {
                return ResourceManager.GetString("EnquiryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiy.
        /// </summary>
        public static string Enquiy {
            get {
                return ResourceManager.GetString("Enquiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date From.
        /// </summary>
        public static string EventDateFrom {
            get {
                return ResourceManager.GetString("EventDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date Time.
        /// </summary>
        public static string EventDateTime {
            get {
                return ResourceManager.GetString("EventDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date To.
        /// </summary>
        public static string EventDateTo {
            get {
                return ResourceManager.GetString("EventDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Information.
        /// </summary>
        public static string EventInformation {
            get {
                return ResourceManager.GetString("EventInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Is Requierd.
        /// </summary>
        public static string FieldIsRequierd {
            get {
                return ResourceManager.GetString("FieldIsRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Admin.
        /// </summary>
        public static string FromAdmin {
            get {
                return ResourceManager.GetString("FromAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Clinet.
        /// </summary>
        public static string FromClinet {
            get {
                return ResourceManager.GetString("FromClinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Active Code.
        /// </summary>
        public static string InvalidActiveCode {
            get {
                return ResourceManager.GetString("InvalidActiveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name Or Password.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Print Names.
        /// </summary>
        public static string IsAllowPrintNames {
            get {
                return ResourceManager.GetString("IsAllowPrintNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Logo.
        /// </summary>
        public static string IsClinetCustomLogo {
            get {
                return ResourceManager.GetString("IsClinetCustomLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Logo.
        /// </summary>
        public static string IsLogoAr {
            get {
                return ResourceManager.GetString("IsLogoAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Names.
        /// </summary>
        public static string IsNamesAr {
            get {
                return ResourceManager.GetString("IsNamesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iso Code.
        /// </summary>
        public static string IsoCode {
            get {
                return ResourceManager.GetString("IsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It Is Already Used.
        /// </summary>
        public static string ItIsAlreadyUsed {
            get {
                return ResourceManager.GetString("ItIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked With Clinet.
        /// </summary>
        public static string LinkedWithClinet {
            get {
                return ResourceManager.GetString("LinkedWithClinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To Your Account.
        /// </summary>
        public static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length Char Is.
        /// </summary>
        public static string MaxLengthCharIs {
            get {
                return ResourceManager.GetString("MaxLengthCharIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Number Is.
        /// </summary>
        public static string MaxNumberIs {
            get {
                return ResourceManager.GetString("MaxNumberIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Length Char Is.
        /// </summary>
        public static string MinLengthCharIs {
            get {
                return ResourceManager.GetString("MinLengthCharIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Number Is.
        /// </summary>
        public static string MinNumberIs {
            get {
                return ResourceManager.GetString("MinNumberIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Enquires.
        /// </summary>
        public static string MyEnquires {
            get {
                return ResourceManager.GetString("MyEnquires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        public static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Bride.
        /// </summary>
        public static string NameBride {
            get {
                return ResourceManager.GetString("NameBride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Groom.
        /// </summary>
        public static string NameGroom {
            get {
                return ResourceManager.GetString("NameGroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Branch.
        /// </summary>
        public static string NoBranch {
            get {
                return ResourceManager.GetString("NoBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Result.
        /// </summary>
        public static string NoMoreResult {
            get {
                return ResourceManager.GetString("NoMoreResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Activated.
        /// </summary>
        public static string NotActivated {
            get {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Count.
        /// </summary>
        public static string NotesCount {
            get {
                return ResourceManager.GetString("NotesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Day.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Hour.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Minute.
        /// </summary>
        public static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Month.
        /// </summary>
        public static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Year.
        /// </summary>
        public static string OneYear {
            get {
                return ResourceManager.GetString("OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opene.
        /// </summary>
        public static string Opene {
            get {
                return ResourceManager.GetString("Opene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Details.
        /// </summary>
        public static string PackageDetails {
            get {
                return ResourceManager.GetString("PackageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Information.
        /// </summary>
        public static string PackageInformation {
            get {
                return ResourceManager.GetString("PackageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Input Types.
        /// </summary>
        public static string PackageInputTypes {
            get {
                return ResourceManager.GetString("PackageInputTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string Packages {
            get {
                return ResourceManager.GetString("Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone It Is Already Used With Another Account.
        /// </summary>
        public static string PhoneItIsAlreadyUsed {
            get {
                return ResourceManager.GetString("PhoneItIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Copy This Code.
        /// </summary>
        public static string PleaseCopyThisCode {
            get {
                return ResourceManager.GetString("PleaseCopyThisCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Names Type.
        /// </summary>
        public static string PrintNamesType {
            get {
                return ResourceManager.GetString("PrintNamesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Names Types.
        /// </summary>
        public static string PrintNamesTypes {
            get {
                return ResourceManager.GetString("PrintNamesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Name Type.
        /// </summary>
        public static string PrintNameType {
            get {
                return ResourceManager.GetString("PrintNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Update.
        /// </summary>
        public static string ProfileUpdate {
            get {
                return ResourceManager.GetString("ProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readed.
        /// </summary>
        public static string Readed {
            get {
                return ResourceManager.GetString("Readed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Active Code To Email.
        /// </summary>
        public static string SendActiveCodeToEmail {
            get {
                return ResourceManager.GetString("SendActiveCodeToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Error Has Been.
        /// </summary>
        public static string SomeErrorHasBeen {
            get {
                return ResourceManager.GetString("SomeErrorHasBeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Not Found.
        /// </summary>
        public static string StateNotFound {
            get {
                return ResourceManager.GetString("StateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Enquiry Already Linked With Clinet.
        /// </summary>
        public static string ThisEnquiryAlreadyLinkedWithClinet {
            get {
                return ResourceManager.GetString("ThisEnquiryAlreadyLinkedWithClinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Days.
        /// </summary>
        public static string TwoDays {
            get {
                return ResourceManager.GetString("TwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Hour.
        /// </summary>
        public static string TwoHour {
            get {
                return ResourceManager.GetString("TwoHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Minute.
        /// </summary>
        public static string TwoMinute {
            get {
                return ResourceManager.GetString("TwoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Months.
        /// </summary>
        public static string TwoMonths {
            get {
                return ResourceManager.GetString("TwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Years.
        /// </summary>
        public static string TwoYears {
            get {
                return ResourceManager.GetString("TwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Branch.
        /// </summary>
        public static string UpdateBranch {
            get {
                return ResourceManager.GetString("UpdateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Country.
        /// </summary>
        public static string UpdateCountry {
            get {
                return ResourceManager.GetString("UpdateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Enquiry.
        /// </summary>
        public static string UpdateEnquiry {
            get {
                return ResourceManager.GetString("UpdateEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Enquiry Type.
        /// </summary>
        public static string UpdateEnquiryType {
            get {
                return ResourceManager.GetString("UpdateEnquiryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Event.
        /// </summary>
        public static string UpdateEvent {
            get {
                return ResourceManager.GetString("UpdateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Package.
        /// </summary>
        public static string UpdatePackage {
            get {
                return ResourceManager.GetString("UpdatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Logo.
        /// </summary>
        public static string UploadLogo {
            get {
                return ResourceManager.GetString("UploadLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name It Is Already Used With Another Account.
        /// </summary>
        public static string UserNameItIsAlreadyUsed {
            get {
                return ResourceManager.GetString("UserNameItIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Pages Privileges.
        /// </summary>
        public static string UsersPagesPrivileges {
            get {
                return ResourceManager.GetString("UsersPagesPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Value.
        /// </summary>
        public static string ValueAr {
            get {
                return ResourceManager.GetString("ValueAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Value.
        /// </summary>
        public static string ValueEn {
            get {
                return ResourceManager.GetString("ValueEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date Time.
        /// </summary>
        public static string VisitDateTime {
            get {
                return ResourceManager.GetString("VisitDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Access To Create Accont.
        /// </summary>
        public static string YouCanNotAccessToCreateAccont {
            get {
                return ResourceManager.GetString("YouCanNotAccessToCreateAccont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Create.
        /// </summary>
        public static string YouCanNotCreate {
            get {
                return ResourceManager.GetString("YouCanNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Update.
        /// </summary>
        public static string YouCanNotUpdate {
            get {
                return ResourceManager.GetString("YouCanNotUpdate", resourceCulture);
            }
        }
    }
}
